Add private keys
rchain-community/rgov pull request #127
Opened 2021-05-18 23:34 UTC by Bill-Keuntje

testing keys needed for python and javascript UI

2021-05-19 00:34 UTC, dckc requested changes
oops. `ReadcapURI` got committed.

2021-05-19 00:34 UTC, dckc commented on ReadcapURI.json
> +{"ReadcapURI" : "rho:id:45qoa694ijuiy6enn5dne3eca8ipechh7si3fjzammp1ycz1tcijc6"}
oops... `ReadcapURI` got committed.

2021-05-19 07:10 UTC, Bill-Keuntje commented on ReadcapURI.json
> +{"ReadcapURI" : "rho:id:45qoa694ijuiy6enn5dne3eca8ipechh7si3fjzammp1ycz1tcijc6"}
> oops... `ReadcapURI` got committed.

Yep. How do I remove it?

2021-05-19 09:35 UTC, dckc commented on ReadcapURI.json
> +{"ReadcapURI" : "rho:id:45qoa694ijuiy6enn5dne3eca8ipechh7si3fjzammp1ycz1tcijc6"}
git commit --amend

Or the equvalent

2021-05-21 17:45 UTC, Bill-Keuntje commented on ReadcapURI.json
> +{"ReadcapURI" : "rho:id:45qoa694ijuiy6enn5dne3eca8ipechh7si3fjzammp1ycz1tcijc6"}
updated by adding two new commits reverting the changes

2021-05-24 07:36 UTC, Bill-Keuntje commented
@w2vy Please let me know if these changes are suitable to your pyrchain/pytest testing.

2021-05-24 21:37 UTC, Bill-Keuntje commented
@dckc New commit reverts incorrectly committed files.

2021-05-31 11:09 UTC, w2vy commented
Repalced by https://github.com/rchain-community/rgov/pull/177

2021-05-31 11:09 UTC, closed without merging