Replacement for branch separate-NETWORKS
rchain-community/rgov pull request #143
Opened 2021-05-21 18:37 UTC by Bill-Keuntje

Move deploy, propose, and NETWORKS into individual files.

2021-05-21 20:42 UTC, dckc requested changes
"Replacement for branch separate-NETWORKS" is phrased in terms of ephemera (a branch name). Commit messages are part of the permanent history of the project.

Please use a commit message that explains the purpose of the commit. I don't understand the purpose of this commit / PR.

But I found at least one or two things that should change.

2021-05-21 20:42 UTC, dckc commented on src/propose.js
> +            setTimeout(propose, 10000);
`setTimeout` is ambient authority.

2021-05-21 20:42 UTC, dckc commented on src/NETWORKS.js
> +function makeNetwork(pattern, obs, val, adm) {
what's the purpose of the `makeNetwork` function? It doesn't seem to have any benefit over writing out the object literal.

2021-05-21 20:42 UTC, dckc commented on src/deploy.js
> +import m from 'mithril';
`m` includes ambient authority, IIRC.

2021-05-21 20:42 UTC, dckc commented on src/NETWORKS.js
> + * @type {{ localhost: net, testnet: net, demo: net, rhobot: net, mainnet: net}} NETWORKS
the syntax is:
```js
/** @type {...} */
const NETWORKS = ...
```

2021-05-21 20:42 UTC, dckc commented on src/NETWORKS.js
> +         })
What is this call to `Object.entries` supposed to do? It looks like a noop.

2021-05-21 20:42 UTC, dckc commented on src/NETWORKS.js
> +export function networkNames() {
`networkNames` might make sense if the purpose were to abstract the representation of `NETWORKS`, but `NETWORKS` is exported, so I don't understand what this function is for.

2021-05-21 23:10 UTC, pfabre31 commented on src/NETWORKS.js
> +         })
Completely agree, I don't actually know what that code was written for

2021-05-21 23:19 UTC, pfabre31 commented
Hi @dckc, thanks for this review. Indeed I think there has been a misunderstanding on the purpose of this PR. 

First, I'd like to say that none of the code blocks that you commented was written by me. All I did was fixing a bunch of bugs on this branch, after @Bill-Keuntje let us know it would be interesting to include the refactoring work of this branch into our branch ballot-ui. And honestly I'm not sure I am the best person to do this refactoring work as I just discovered the code and that there are still a lot of things I don't quite understand. Maybe the person who started this refactoring ? Do you think there is still a lot to do ?
Don't get me wrong, I am super motivated to work on this, I am just trying to find the way to be the most efficient. And I do believe that this is by working on UI/UX. Now as this UI/UX should be based on a refactoring, I wonder what the next step is. Maybe we should set up a call to discuss it.

2021-05-22 04:50 UTC, Bill-Keuntje commented
This PR is a first step to allow multiple UIs to be developed for various rgov projects/features using the same code and at the same time avoid the inevitable conflicts/dependencies in participate.js (which is the development interface).

2021-06-25 19:06 UTC, Bill-Keuntje commented
@dckc @jimscarver @w2vy @David405 @pfabre31 
Shall we abandon this effort and continue with what we have (which works)?

2021-07-02 08:12 UTC, Bill-Kunj commented
Given no active response, this is abandoned. Opening new issue to refactor participate.js #217

2021-07-02 08:12 UTC, closed without merging