Implement syntax highlighting
rchain-community/rgov pull request #190
Opened 2021-06-08 20:48 UTC by Bill-Keuntje

Closes syntax highlighting #134

2021-06-08 20:54 UTC, dckc commented on package.json
> +    "eslint": "^7.28.0",
did you upgrade eslint in this commit on purpose?

2021-06-08 20:55 UTC, dckc commented on src/participate.html
> +  <title>RGOV developer interface</title>
Did you change the title on purpose? I don't see anything about it in the commit message.

2021-06-08 20:58 UTC, dckc commented on src/participate.js
> +import './prism-rholang.css';
What does that do? If it mutates global state, that isn't consistent with ocap discipline. Please find another way.

2021-06-08 20:58 UTC, dckc commented on src/participate.js
> +Prism.hooks.add('before-sanity-check', function (env) {
more mutating global mutable state

2021-06-08 20:59 UTC, dckc commented on src/participate.js
> +      if (value !== null) value.replace(/<br\/?>/g, "\n");
I don't `value.replace(...)` doesn't mutate `value`. I don't think this does what you you're thinking.

2021-06-08 21:01 UTC, dckc commented on src/participate.js
> +    Prism.highlightElement(result_element);
more global mutable state?

2021-06-08 21:01 UTC, dckc commented on src/participate.js
> +    let result_element = document.querySelector("#highlighting");
`document` is accessed ambiently

2021-06-09 03:39 UTC, Bill-Keuntje commented on package.json
> +    "eslint": "^7.28.0",
No

2021-06-09 03:39 UTC, Bill-Keuntje commented on src/participate.html
> +  <title>RGOV developer interface</title>
Yes, this is intentional.
I agree the commit message is underwhelming.

2021-06-09 03:40 UTC, Bill-Keuntje commented on src/participate.html
> -  <address>
Trying to conserve space in the display.
Putting it back is no-big-deal once I figure out the CSS necessary.

2021-06-09 03:43 UTC, Bill-Keuntje commented on src/participate.js
> +Prism.hooks.add('before-sanity-check', function (env) {
Necessary for proper function of highlighting.
Should I instead create a rgov-prism.js that encapsulates this?

2021-06-09 03:48 UTC, Bill-Keuntje commented on src/participate.js
> +    let result_element = document.querySelector("#highlighting-content");
Agreed. But we create a new element "highlighting-content" every time a different action is selected.  In order to fix this, that means creating a static "highlighting-content", "highlighting", "editing" elements and completely re-writing actionControl() to not use freeze() as a return value?

2021-06-09 03:49 UTC, Bill-Keuntje commented on src/participate.js
> +    let result_element = document.querySelector("#highlighting");
more like previous comment? https://github.com/rchain-community/rgov/pull/190#discussion_r647944372

2021-06-09 03:49 UTC, Bill-Keuntje commented on src/prism-rholang.js
> +import Prism from 'prismjs';
The object is specific to participate scope.

2021-06-09 03:51 UTC, Bill-Keuntje commented on src/participate.js
> +import './prism-rholang.css';
I'm not a CSS guy, this is the way I found that worked. How would we include this other than changing the HTML?

2021-06-09 03:52 UTC, Bill-Keuntje commented on src/participate.js
> +setRholangHighlight(Prism);
Agreed. Create local prism.js? See https://github.com/rchain-community/rgov/pull/190#discussion_r647942892

2021-06-09 03:53 UTC, Bill-Keuntje commented on src/participate.js
> +      if (value !== null) value.replace(/<br\/?>/g, "\n");
Agreed.

2021-06-09 04:15 UTC, dckc commented on package.json
> +    "eslint": "^7.28.0",
I don't think it's a problem; but it belong in its own commit... or at the very least there should be a few words about it in the message for this commit.

If I'm looking at `git blame` or `git log` for `package.json`, i want it to be very clear exactly why we upgraded eslint. If the subject (1st line) of the commit message is "Implement syntax highlighting", that suggests syntax highlighting needed an upgrade to eslint somehow. If we're just upgrading for the sake of staying current, a separate "update eslint devDependencies" would be more clear. I can look past the subject of an "Implement syntax highlighting" commit message if there's something about it in the body, but that's inconvenient.

2021-06-09 04:17 UTC, dckc commented on src/participate.html
> -  <address>
Alright, but that seems unrelated to syntax highlighting. I suggest leaving it to a separate PR or at least a separate commit.

2021-06-09 04:21 UTC, dckc commented on src/participate.js
> +setRholangHighlight(Prism);
Er.. then it would be globally mutable state in a `prism.js` module.

The purpose of #186 was to be clear: `index.js` should be the only exception to ocap discipline. It uses whatever tricks are necessary to get access to the outside world and then passes it to the ocap-happy code.

2021-06-09 04:22 UTC, dckc commented on src/participate.js
> +import './prism-rholang.css';
I have no problem with changing the (static) HTML to include a `<link href="./prism-rholang.css" />`. That seems straightforward.

2021-06-09 04:23 UTC, dckc commented on src/participate.js
> +Prism.hooks.add('before-sanity-check', function (env) {
mutable state has to be passed around explicitly; see above.

2021-06-09 04:25 UTC, dckc commented on src/participate.js
> +    let result_element = document.querySelector("#highlighting-content");
Why create a new element? I don't follow.

_I suspect github comments don't provide enough bandwidth for this topic. Here's hoping we get to talk about it._

2021-06-09 04:26 UTC, dckc commented on src/prism-rholang.js
> +import Prism from 'prismjs';
line 4 does nothing, as far as I can tell. The occurence of `Prism` that it introduces is never referenced.

2021-06-10 17:45 UTC, Bill-Keuntje commented on src/participate.js
> +setRholangHighlight(Prism);
Moving Prism to index.js is fine.

2021-06-10 17:47 UTC, Bill-Keuntje commented on src/participate.js
> +Prism.hooks.add('before-sanity-check', function (env) {
Agreed. 
Belongs in index.js

2021-06-10 17:47 UTC, Bill-Keuntje commented on src/prism-rholang.js
> +import Prism from 'prismjs';
Yep. Didn't clean this up before commiting.

2021-06-10 17:56 UTC, Bill-Keuntje commented on src/participate.js
> +import './prism-rholang.css';
Agree

2021-06-10 17:57 UTC, Bill-Keuntje commented on src/participate.html
> -  <address>
Sure. Would you like me to create a new branch with new commits and a new PR to *address* this? ;)

2021-06-10 18:00 UTC, Bill-Keuntje commented on package.json
> +    "eslint": "^7.28.0",
I have to admit, I don't look at ```git blame``` much. So I don't completely get this.
Creating a large number of commits creates problems during a review as well.
I'll try and do better next time. ;)

2021-06-10 18:45 UTC, Bill-Keuntje commented
New commits available for review.

2021-06-10 20:15 UTC, dckc commented on src/participate.html
> -  <address>
I'll stand by until you mark this pr not-draft. I expect this to be cleaned up by then, yes.

2021-06-11 04:32 UTC, Bill-Keuntje commented on src/participate.js
> +    Prism.highlightElement(result_element);
Yep. Will be resolved.

2021-06-12 18:34 UTC, Bill-Keuntje commented
@SJellen, I could really use some help with CSS on this. Can you help?

2021-06-12 19:05 UTC, David405 commented
@Bill-Keuntje I guess I could be of help, I think I am well enough to do some technical work now

2021-06-14 18:08 UTC, dckc commented on src/participate.html
> -  <address>
I don't see why this was marked resolved. It's not.

2021-06-14 18:09 UTC, dckc requested changes
my comment about `<address>` is not addressed.

2021-06-15 20:49 UTC, dckc commented on src/prism-rholang.js
> +  // Maybe a URI should be anything inside `back-ticks`?
yes:

```
token UriLiteral ('`' ((char - ["\\`"]) | ('\\' ["`\\"]))* '`') ;
```
-- https://github.com/rchain/rchain/blob/9e8def056f025729e13b56e38ae30ca6da847484/rholang/src/main/bnfc/rholang_mercury.cf#L147

2021-06-15 21:04 UTC, Bill-Keuntje commented on src/prism-rholang.js
> +  // Maybe a URI should be anything inside `back-ticks`?
e: https://github.com/rchain-community/rgov/pull/190/commits/eb10815d5eddf69b76e8cadff8b40fefaeb1d9a5

2021-06-15 21:09 UTC, Bill-Keuntje commented
> my comment about `<address>` is not addressed.

Done: https://github.com/rchain-community/rgov/pull/190/commits/2cf71b0ad7b470ae67c907523b2c2744cc234676

2021-06-16 21:28 UTC, David405 commented
@Bill-Keuntje is there any reason in particular you made the rholang code fixed at the bottom half of the screen? can this be changed?

2021-06-16 23:29 UTC, dckc commented on src/participate.html
> +  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="
why is package-lock.json changing in a commit about a resizable window?!

Please review your diffs when you write your commit messages.

Also, please keep the 1st line of the commit message short. Note how github renders this one:

```
made the rholang textarea a resizable window, removed bottom fixed di…
…v, adjusted syntax, background colours from high contrast to more eye friendly colours
```

2021-06-16 23:34 UTC, dckc requested changes
adding a dependency on interactjs is not mentioned the commit message, nor in comments. Let's not silently add dependencies. I suggest adding an issue to consider the benefits and only add the dependency once we're agreed.

2021-06-16 23:34 UTC, dckc commented on src/participate.html
> +  <script src="https://unpkg.com/interactjs/dist/interact.min.js"></script>
hmm... another dependency... please add an issue about this and let's discuss the risks / costs / benefits of it.

2021-06-16 23:38 UTC, dckc commented on src/participate.html
> +  <title>RGOV developer interface</title>
Why change the title? How is that related to syntax highlighting?

2021-06-16 23:48 UTC, dckc requested changes
I'm not able to edit the code after choosing an action. That seems like a major regression.

2021-06-17 09:41 UTC, David405 commented on src/participate.html
> +  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="
The ```package-lock.json``` change reflects newer versions of dependencies that got installed during ```npm install```, probably I should have removed it from staged changes before committing but I don't see that breaking anything.

Your point on the commit message is noted, although, I just wanted the message to capture explicitly the details of the work.

2021-06-17 10:01 UTC, David405 commented
> I'm familiar with boostrap, but again, let's not add dependencies silently, without even a mention in the commit message.
> 
> Did you measure the performance impact?
> 
> Where is bootstrap used? I don't see any relevant markup.

Let me address both my use of bootstrap and interactjs here, I intentionally did not install these libraries as dependencies because of the concerns you raised here.

PERFORMANCE:
I used both of them as CDN to prevent any problem that may arise in terms of performance as these are their minified versions, load times for CDNs on average are around 50ms which shouldn't cause any noticeable delay, also, I believe nearly every users' browsers in the world should have Bootstrap CDN cached as we all have most likely have visited a bootstrap website at one point in time.

USAGE: 
Interact.js was used to make the rholang textarea resizable from all corners or part of the textarea, this helps a lot with the User Experience, I couldn't find a way to do to this with raw CSS or JS( _I could only do that from one corner using CSS_ ), that was why I used an external library, if I figure that out with raw CSS or JS, then we could do away with interact.js.

Bootstrap was used to give some subtle styling effect on the buttons, padding around the edges, fonts and colours, its not a necessity but it just provides some nice visual effects and it doesn't cost much on performance.

2021-06-17 10:04 UTC, David405 commented
> I'm not able to edit the code after choosing an action. That seems like a major regression.

I am not sure if this was directed at me but I didn't test for editing code before I made changes, so I am not sure how the changes I made broke that, I will check to see if that is coming from me.

2021-06-17 15:31 UTC, Bill-Keuntje commented on src/rgov-development.css
> +	position: relative;
This results in the <textarea> not being layered on top of the <pre><code> elements, making the highlighted code non-editable.

2021-06-17 15:32 UTC, Bill-Keuntje commented on src/rgov-development.css
> +	color: #98d0d1;
Perhaps this should be a darker color? It looks almost white on my display.

2021-06-17 15:35 UTC, Bill-Keuntje commented on src/participate.html
> +  <title>RGOV developer interface</title>
Is the problem the new title, or that it changed in this PR?

2021-06-17 15:40 UTC, Bill-Keuntje commented on src/rgov-development.css
> +	position: relative;
See https://css-tricks.com/creating-an-editable-textarea-that-supports-syntax-highlighted-code/

2021-06-17 15:48 UTC, Bill-Keuntje commented on src/participate.html
> +  <script src="https://unpkg.com/interactjs/dist/interact.min.js"></script>
Do we want to enable phone/tablet developers? If so, I don't see a reason for a lengthy discussion about this dependency. If not, then this might be too heavy.

2021-06-17 15:58 UTC, Bill-Keuntje commented
> I'm not able to edit the code after choosing an action. That seems like a major regression.

@David405 This is the result of changing the 'fixed' to 'relative' in the CSS.

2021-06-17 16:07 UTC, Bill-Keuntje commented on src/participate.html
> +  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="
> > I'm familiar with boostrap, but again, let's not add dependencies silently, without even a mention in the commit message.
> > Did you measure the performance impact?
> > Where is bootstrap used? I don't see any relevant markup.
> 
> Let me address both my use of bootstrap and interactjs here, I intentionally did not install these libraries as dependencies because of the concerns you raised here.
> 
> PERFORMANCE:
> I used both of them as CDN to prevent any problem that may arise in terms of performance as these are their minified versions, load times for CDNs on average are around 50ms which shouldn't cause any noticeable delay, also, I believe nearly every users' browsers in the world should have Bootstrap CDN cached as we all have most likely have visited a bootstrap website at one point in time.
> 
> USAGE:
> Interact.js was used to make the rholang textarea resizable from all corners or part of the textarea, this helps a lot with the User Experience, I couldn't find a way to do to this with raw CSS or JS( _I could only do that from one corner using CSS_ ), that was why I used an external library, if I figure that out with raw CSS or JS, then we could do away with interact.js.
> 
> Bootstrap was used to give some subtle styling effect on the buttons, padding around the edges, fonts and colours, its not a necessity but it just provides some nice visual effects and it doesn't cost much on performance.

I've got no problem with bootstrap. The visuals are better.

2021-06-18 00:44 UTC, David405 commented on src/rgov-development.css
> +	position: relative;
Oh I see

2021-06-18 00:45 UTC, David405 commented on src/rgov-development.css
> +	color: #98d0d1;
Let me make some changes

2021-06-18 00:50 UTC, David405 commented on src/participate.html
> +  <script src="https://unpkg.com/interactjs/dist/interact.min.js"></script>
@Bill-Keuntje I didn't see a need to create a separate issue for this as I believe this isn't an important dependency....I only added it to allow users change the size of the text area from any direction, not necessarily mobile users but PC users, we could as well go with the default CSS way of resizing textarea.

2021-06-18 00:57 UTC, Bill-Keuntje commented on src/participate.html
> +  <script src="https://unpkg.com/interactjs/dist/interact.min.js"></script>
Raw CSS would be fine if we can get a usable interface. But, a discussion about enabling phone/tablet developer use is also worthy.
Let's remove the dependency for now as long as we get the UI/UX we want.

2021-06-18 01:31 UTC, dckc commented on src/participate.html
> +  <title>RGOV developer interface</title>
The problem is that it's in this PR without justification. The problem is that the scope of this PR keeps creeping. It's sort of impossible to review for that reason.

2021-06-18 01:38 UTC, dckc commented
synchronization between the action and the form fields doesn't seem to be working. I flipped back and forth between various actions a few times, and I get a bunch of unrelated fields:

![image](https://user-images.githubusercontent.com/150986/122492720-e39ce680-cfab-11eb-85de-684891fc8fd9.png)

2021-06-18 02:22 UTC, Bill-Keuntje commented on src/participate.html
> +  <title>RGOV developer interface</title>
I understand ```creep```.
I just don't feel like changing a little text is a big deal.
If it is, then I'll change it back.
NP - expect another commit.

2021-06-18 02:22 UTC, Bill-Keuntje commented on src/participate.html
> +  <title>RGOV developer interface</title>
I'm glad we had this discussion. :+1:

2021-06-18 03:35 UTC, Bill-Keuntje commented
> synchronization between the action and the form fields doesn't seem to be working. I flipped back and forth between various actions a few times, and I get a bunch of unrelated fields:
> 
> ![image](https://user-images.githubusercontent.com/150986/122492720-e39ce680-cfab-11eb-85de-684891fc8fd9.png)

Yep. This happens.
It's uncertain why. Rigorous tracing through the code shows nothing other than fieldControls() is invoked twice. No indication as to why these multiple invocations create duplicate input items.
I've gone though the code and can't understand why 'past' invocation of fieldControls() would allow 'present' invocations to include 'past' field elements.
I suspect that fieldControls() is being invoked in multiple places, at least on of which is unexpected - possibly as a result of Mithril automation.
Research on the web supposes we should be creating our HTML elements through Mithril instead of through the use of ```html`<markup>`````

2021-06-24 18:09 UTC, jimscarver commented
I am still unable to edit on branch syntax-highlight

2021-06-24 18:16 UTC, Bill-Keuntje commented
> I am still unable to edit on branch syntax-highlight

Where are you trying this? https://deploy-preview-190--rgov1.netlify.app/ works for me.

2021-06-24 18:19 UTC, Bill-Keuntje commented
@dckc I see that the dev-environment label has been removed.
Is syntax highlighting not part of a development environment?
I'm confused....

2021-06-24 18:20 UTC, Bill-Keuntje commented
> Okay, can you mention them?

Yes, but this is probably best done over a zoom call.

2021-06-24 18:54 UTC, dckc commented
> @dckc I see that the dev-environment label has been removed.
> Is syntax highlighting not part of a development environment?
> I'm confused....

I didn't see a clear pattern to the use of the **dev-environment** label, so I checked the description in the [Labels](https://github.com/rchain-community/rgov/labels) key and found "Anything affecting bootstrap tooling". Syntax highlighting doesn't affect bootstrap tooling, does it?

2021-06-24 19:00 UTC, jimscarver commented
I guess I needed to pull that branch, It works now except the cursor jumps to the end of the code after typing a character much of the time. I end up typing at the bottom. The same happens at https://deploy-preview-190--rgov1.netlify.app/

2021-06-24 19:07 UTC, Bill-Keuntje commented
> > @dckc I see that the dev-environment label has been removed.
> > Is syntax highlighting not part of a development environment?
> > I'm confused....
> 
> I didn't see a clear pattern to the use of the [dev-environment](https://github.com/rchain-community/rgov/labels/dev%20environment) label, so I checked the description in the [Labels](https://github.com/rchain-community/rgov/labels) key and found "Anything affecting bootstrap tooling". Syntax highlighting doesn't affect bootstrap tooling, does it?
> 
> Maybe better to rename the label to **bootstrap-tooling**? Make another for **actions-ui**?

Seems right to me. Labels updated with new descriptions and names.

2021-06-24 19:08 UTC, Bill-Keuntje commented
Accidentally closed this PR. Reopened.

2021-06-24 19:10 UTC, Bill-Keuntje commented
> I guess I needed to pull that branch, It works now except the cursor jumps to the end of the code after typing a character much of the time. I end up typing at the bottom. The same happens at https://deploy-preview-190--rgov1.netlify.app/

Yep. That happens. Not sure where it is coming from. I suspect merging the ocap refactoring introduced a few bugs.

2021-06-24 19:19 UTC, Bill-Keuntje commented
> adding a dependency on interactjs is not mentioned the commit message, nor in comments. Let's not silently add dependencies. I suggest adding an issue to consider the benefits and only add the dependency once we're agreed.

@dckc This is resolved, no? Please review again and remove the block on the merge.

2021-06-24 19:19 UTC, Bill-Keuntje commented
> I'm not able to edit the code after choosing an action. That seems like a major regression.

@dckc This has been addressed. Please review again and remove the block on the merge.

2021-06-24 20:39 UTC, Bill-Keuntje commented
> > I guess I needed to pull that branch, It works now except the cursor jumps to the end of the code after typing a character much of the time. I end up typing at the bottom. The same happens at https://deploy-preview-190--rgov1.netlify.app/
> 
> Yep. That happens sometimes. Not sure where it is coming from. I suspect merging the ocap refactoring introduced a few bugs.

@jimscarver 
I'm still testing, but I believe this is the result of the call to fixIndent() in participate.js.

2021-06-24 20:43 UTC, dckc commented
> Do we still need fixIndent()?

Well, no; we never did need automatic indentation. But it's nice to have. Is there a reason to get rid of it?

2021-06-24 21:05 UTC, jimscarver approved these changes
It works almost perfectly. The cursor jumps to the end of the code sometimes when you type in the code. I think it is good enough to merge with am expectation that the final bug is fixed soon.

2021-06-25 03:45 UTC, David405 commented
@jimscarver that was a problem with fixIndent() function, it has been resolved now

2021-06-25 13:09 UTC, dckc commented
Really? I still see the cursor jumping problem: when I select check balance, then click at the beginning of, say, line 11, then type `s`, the `s` gets inserted but then the cursor immediately jumps to the bottom.

It's as if we're calling `fixIndent()` on every character typed instead of when the user tabs out of the box.

2021-06-25 13:23 UTC, dckc commented
I still see the field sync problem (#29) when testing at https://deploy-preview-190--rgov1.netlify.app/

2021-06-25 14:37 UTC, David405 commented
I did a fix on both the UX and functionality problems surrounding the textarea, albeit, _a not so elegant fix_, but it gets the job done.

There is currently a known problem though, the cursor disappears randomly on chromium-based browsers, you can still type correctly, just that this makes the experience somewhat stressful. 

Everything seems to work fine on Firefox.

2021-06-25 16:01 UTC, dckc commented
now I get an invisible cursor and no auto-indent

2021-06-25 17:10 UTC, Bill-Keuntje commented
> > Do we still need fixIndent()?
> 
> Well, no; we never did need automatic indentation. But it's nice to have. Is there a reason to get rid of it?

The thing that's twerking my brain is the automatic indentation does not match vscode. So, rholang code in vscode that looks and works just fine gets completely re-formated in the web interface; this results in a "What just happened to my code?" question for the user.

2021-06-25 17:16 UTC, Bill-Keuntje commented
> now I get an invisible cursor and no auto-indent
> 
> (on brave; chromium based)

Yep. The immediate fix to the cursor popping to the bottom of the textarea is removing fixIndent() - which, of course, eliminates auto-indent. There's gotta be a way to do this, but see my https://github.com/rchain-community/rgov/pull/190#issuecomment-868710438 on auto-indent generally.
Research on the web indicates that the invisible cursor may be a result of a bug in chromium combined with the way Prism does <span> highlighting. Still checking on this - please stand by. :)

2021-06-25 17:39 UTC, Bill-Keuntje commented on src/rgov-development.css
> +	border: transparent !important;
Forgive me, I'm not a CSS guy. What does the ```!important``` do here?

2021-06-25 17:40 UTC, Bill-Keuntje commented on src/rgov-development.css
>  }
@dckc @jimscarver @David405
I'm not a github guru. Is there a way to have github add a missing newline at the end of certain types of files?

2021-06-25 18:04 UTC, dckc commented on src/rgov-development.css
>  }
github won't mess with the bytes of your files. newlines have to be right in the committed bytes.

2021-06-25 18:07 UTC, Bill-Keuntje commented on src/participate.js
> +      // The browser puts in <br> or <br/> instead of newline. Fix that.
@dckc 
https://github.com/rchain-community/rgov/pull/190#issuecomment-868710438
The original code used ```onchange``` when assigning ```term```. The new code uses ```oninput``` in order to make sure highlighting gets updated. If we continue to use fixIndent(), then we need to find a new place to call it.

2021-06-25 18:22 UTC, Bill-Keuntje commented on src/rgov-development.css
>  }
Then, is there a way to put a ```git push``` or ```git commit``` trigger in place for this?

2021-06-25 18:23 UTC, dckc commented on src/participate.js
> +      // The browser puts in <br> or <br/> instead of newline. Fix that.
Squeezing indentation inside `fixIndent` was perhaps useful for prototyping. But better to do highlighting in `oninput` and then `fixIndent` in `onchange`.

2021-06-25 18:39 UTC, dckc commented on src/rgov-development.css
>  }
You can have things that stop you from doing the wrong thing... either hooks on your local git ("no, you can't commit that; it doesn't have a newline") or as a github action ("no, you can't merge that PR; it doesn't have a newline")

2021-06-25 18:43 UTC, Bill-Keuntje commented on src/rgov-development.css
>  }
Can you point me to the git/github resources for this?

2021-06-25 18:52 UTC, Bill-Keuntje commented on src/participate.html
> +  <script defer>
@dckc Are there ocap concerns here?

2021-06-25 19:28 UTC, dckc commented on src/participate.html
> +  <script defer>
well, yes, it could be cleaner, but the comment is sufficient rationale for allowing a `Work In Progress TODO` sort of thing.

2021-06-25 21:48 UTC, Bill-Keuntje commented
So, I've fixed the disappearing cursor (I think).
@David405 The new code from https://github.com/rchain-community/rgov/pull/190/commits/ee5d7789e19a45b1a35bc4f9fb25c6a278a0e043 removed the ```<textarea>``` (which is awesome), and along with it went the ```oninput``` and ```onchange``` handlers to update the syntax highlighting when a user types. That ```onXXX``` code needs to be in the ```<pre>``` or ```<code>``` element now (I think. It may be the ```<div>``` element instead).

After that, I think we have it. *Yay*

2021-06-25 22:20 UTC, Bill-Keuntje commented on src/participate.js
> +      // The browser puts in <br> or <br/> instead of newline. Fix that.
@David405 Can we put ```fixIndent``` back in without breaking what we currently have working?

2021-06-26 01:40 UTC, dckc commented
I still see the field sync problem (#29). In fact, I see a button sync problem too:

![Screenshot at 2021-06-25 20-37-35](https://user-images.githubusercontent.com/150986/123497835-5255f180-d5f5-11eb-90b8-de9ae6c4d222.png)

and auto-indent doesn't happen when I tab out of the edit area.

2021-06-26 14:24 UTC, jimscarver commented
I am getting extra fields. Fields from the prior action seem to be retained but not used.
![image](https://user-images.githubusercontent.com/3037201/123516155-b4037380-d668-11eb-95dd-4f2ffe97ce16.png)

2021-06-27 19:48 UTC, Bill-Keuntje commented
@dckc @jimscarver Multiple, repeated fields bug fixed: https://github.com/rchain-community/rgov/pull/190/commits/9191b9fe28f14827f6507ecd3c401b6f47d080bb, https://github.com/rchain-community/rgov/pull/190/commits/a20a2578c6819cc6e60a10d24d625980a5d3eb05, https://github.com/rchain-community/rgov/pull/190/commits/898cb8cd6e3e457f479773f5f3ff23d906c3f88a
Check out the new netlify: https://deploy-preview-190--rgov1.netlify.app/.

@David405 The only functional feature remaining is ```oninput``` https://github.com/rchain-community/rgov/pull/190#issuecomment-868850459

@David405 There are probably some CSS updates required to better align the ```<code>``` element better with the ```<pre>``` element

2021-06-27 21:23 UTC, dckc commented
field sync seems ok, but auto-indent doesn't seem to work.

2021-06-28 03:26 UTC, Bill-Keuntje commented on src/rgov-development.css
>  }
@dckc Are there templates for these things somewhere?

2021-06-28 03:27 UTC, Bill-Keuntje commented
> > my comment about `<address>` is not addressed.
> 
> @dckc Done: [2cf71b0](https://github.com/rchain-community/rgov/commit/2cf71b0ad7b470ae67c907523b2c2744cc234676)

@dckc please honor re-review on this

2021-06-28 03:29 UTC, Bill-Keuntje commented
> > adding a dependency on interactjs is not mentioned the commit message, nor in comments. Let's not silently add dependencies. I suggest adding an issue to consider the benefits and only add the dependency once we're agreed.
> 
> @dckc [#190 (review)](https://github.com/rchain-community/rgov/pull/190#pullrequestreview-685746106) is resolved by removing interactjs? Please review again and remove the block on the merge.

@dckc please honor re-review on this

2021-06-28 03:32 UTC, Bill-Keuntje commented
> field sync seems ok, but auto-indent doesn't seem to work.

Yep. But, I'm not sure we still need auto-indent? https://github.com/rchain-community/rgov/pull/190#issuecomment-868710438

2021-06-28 04:39 UTC, dckc commented
> @dckc The thing that's twerking my brain is the automatic indentation does not match vscode. So, rholang code in vscode that looks and works just fine gets completely re-formated in the web interface; this results in a "What just happened to my code?" question for the user.

Completely re-formatted? How many ways are there to format code with curly-brace matching? Got an example of rholang in vs-code that looks so different that it's disorienting?

2021-06-28 04:57 UTC, dckc commented
> @dckc please honor re-review on this [720f626](https://github.com/rchain-community/rgov/commit/720f626ec71d5ee59534dbab6b1c38fc9da2fc19)

I'm struggling to reproduce the 10KLOC of changes to `package-lock.json`. When I checkout master, then replace `package.json` with the one from this branch, then `npm install`, I get 1K of changes, not 10K.

```
$ git status
On branch master
...
	modified:   package-lock.json
	modified:   package.json

$ git diff|wc
    1075    2668   45027
```

2021-06-28 16:41 UTC, Bill-Keuntje commented
> > @dckc The thing that's twerking my brain is the automatic indentation does not match vscode. So, rholang code in vscode that looks and works just fine gets completely re-formated in the web interface; this results in a "What just happened to my code?" question for the user.
> 
> Completely re-formatted? How many ways are there to format code with curly-brace matching? Got an example of rholang in vs-code that looks so different that it's disorienting?

Well, I suppose you could take a look at peekInbox.rho in vscode and then in the web interface.
However, I'm guessing this could easily turn into a discussion of code format/style, and those discussions usually take forever without concluding too much. We don't have any novice developers on-board right now. If someone complains about the changing indenting in the future, we can discuss it at that time.
I'll work on adding it back.

2021-06-28 22:23 UTC, dckc commented on src/participate.html
> +  <script defer>
hm. now the TODO comment is gone.

2021-06-28 22:33 UTC, dckc commented on src/participate.html
> +  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="
I strongly recommend closing this PR and making a new one that only has the relevant changes without all the undoing and redoing.

The package-lock.json changes don't look right to me.

When I checkout master, then replace `package.json` with the one from this branch, then `npm install`, I get 1K of changes, not 10K.

```
$ git status
On branch master
...
	modified:   package-lock.json
	modified:   package.json

$ git diff|wc
    1075    2668   45027
```

2021-06-29 02:09 UTC, Bill-Keuntje commented on src/participate.html
> +  <script defer>
Disappearing cursor is fixed. https://github.com/rchain-community/rgov/pull/190/commits/f89e5b72e40ef36e7f814b6b939c231733427615
I guess I'll add a "Work in progress for the ocap concerns"

2021-06-30 04:54 UTC, Bill-Keuntje commented
> So, I've fixed the disappearing cursor (I think) [999ece5](https://github.com/rchain-community/rgov/commit/999ece5ae402c8d0af084b234d6b9c69e5237807).
> @dckc @jimscarver Please test and verify
> 
> @David405 The new code from [ee5d778](https://github.com/rchain-community/rgov/commit/ee5d7789e19a45b1a35bc4f9fb25c6a278a0e043) removed the `<textarea>` (awesome), and along with it went the `oninput` and `onchange` handlers to update the syntax highlighting when a user types. It also breaks `deploy` since `state.term` is never updated.
> That `onXXX` code needs to be in the `<pre>` or `<code>` element now (I think. It may be the `<div>` element instead).
> 
> After that, I think we have it. _Yay_

@David405 Every attempt I've made to include ```oninput``` has resulted in the cursor bouncing around - either top or bottom. I'm not sure removing the ```<textarea>``` was the best choice.

At this point, I'm inclined to agree with @dckc that we need to abandon this branch and create a new branch with the working changes. I will work on doing so tomorrow - it may take a couple of days to get it right. I'm opening a new issue for it.

@dckc @jimscarver @David405 @w2vy if you have any specific requests before I proceed, now's the time.

2021-06-30 05:05 UTC, Bill-Keuntje commented
> So, I've fixed the disappearing cursor (I think) [999ece5](https://github.com/rchain-community/rgov/commit/999ece5ae402c8d0af084b234d6b9c69e5237807).
> @dckc @jimscarver Please test and verify
> 
> @David405 The new code from [ee5d778](https://github.com/rchain-community/rgov/commit/ee5d7789e19a45b1a35bc4f9fb25c6a278a0e043) removed the `<textarea>` (awesome), and along with it went the `oninput` and `onchange` handlers to update the syntax highlighting when a user types. It also breaks `deploy` since `state.term` is never updated.
> That `onXXX` code needs to be in the `<pre>` or `<code>` element now (I think. It may be the `<div>` element instead).

It turns out that ```<textarea>``` triggers events that neither ```<pre contentEditable>``` nor ```<code contentEditable>``` trigger. So, ```oninput``` and ```onchange``` need to be on something that generates them. I think we're stuck with a ```<textarea>``` and the resulting CSS difficulties to do _both_ ```oninput``` and ```onchange``` events.

> 
> After that, I think we have it. _Yay_

2021-06-30 15:32 UTC, dckc commented
> @dckc is there any problem with grabbing the rholang code from the appropriate HTML element when we deploy? Or is `state.term` necessary (according to ocap) when we execute a rholang explore/deploy?

as long as access to the HTML element is passed in explicitly, both designs adhere to ocap discipline.

But using `state` everywhere but one place smells like bad design.

2021-07-02 08:15 UTC, Bill-Kunj commented
Too complicated. Replaced by branch (and future pull request) https://github.com/rchain-community/rgov/tree/214-dev-interface.

2021-07-02 08:15 UTC, closed without merging