Pyrgov testing cleanup
rchain-community/rgov pull request #203
Opened 2021-06-21 00:59 UTC by w2vy

pyrgov and testing cleanup

Please review to make sure I hit all issues.

2021-06-21 15:25 UTC, dckc requested changes

2021-06-21 15:25 UTC, dckc commented on pyrgov/README.md
> +new1 = PrivateKey.generate()
This uses ambient authority. I don't consider that exemplary.

If there's a reason not to use ocap discipline, please document it.

Otherwise, as noted in CONTRIBUTING.md, this project uses ocap discipline. See https://github.com/dckc/awesome-ocap/wiki/DisciplinedPython for how to do this in python.

2021-06-22 03:00 UTC, w2vy commented on pyrgov/README.md
> +new1 = PrivateKey.generate()
I am sorry I have absolutely NO clue what you mean

2021-06-22 03:04 UTC, w2vy commented
I have updated the test_voting.py script which emulates the voting demo, but the branch does not have the inbox fix so the test fails. Can we approve the pull and then fix any issues in the independent file test_voting.py?

2021-06-22 03:36 UTC, dckc commented on pyrgov/README.md
> +new1 = PrivateKey.generate()
What's the first word on the linked page that is not completely clear?

2021-06-23 22:59 UTC, Bill-Keuntje commented on pyrgov/README.md
> +new1 = PrivateKey.generate()
I'm not sure that our testing code needs to observe ocap. Certainly not initially.

2021-06-23 23:02 UTC, Bill-Keuntje approved these changes
Looks like what we talked about.

2021-06-23 23:19 UTC, dckc commented on pyrgov/README.md
> +new1 = PrivateKey.generate()
The ocap discipline project norms in CONTRIBUTING apply to test code as well as anything else.

Again, if there's a reason not to use ocap discipline in this code, please document it.

2021-06-24 11:26 UTC, w2vy commented
The test_voting script works showing delegated and non-delegated voting.
This branch does not have the fix_inbox changes so I would like to have this pull request completed
any issues be made against master to allow for resolution of any issued against a working code base

2021-06-24 11:28 UTC, w2vy commented
I think I marked this ready for review, did that take it out of draft and make it "a proper pull request"?

2021-06-24 11:37 UTC, w2vy commented on pyrgov/README.md
> +new1 = PrivateKey.generate()
@dckc It looks like a comment I made didn't quite make it...

I understand many words, but there are concepts that are unclear.
To start with "ambient authority" and "I don't consider that exemplary." really make me feel like you are simply talking down to me, which really does not help solve the problem.

I googled "ocap discipline" and found discussions talking about USING it, but not much that clearly explained what it is.

It would be far better if any issued raised were specific as to what is wrong with the code and possibly suggestions on what it should do.

In the link you referenced I did see a comment about using pathlib instead of open(str) so that may be something

Is that the problem with the code?

But the quoted code did not use open, so maybe there is more

2021-06-24 18:02 UTC, dckc commented on pyrgov/README.md
> +new1 = PrivateKey.generate()
Good point: "ambient authority" is not defined in/near the DisciplinedPython page.

I apologize for being terse and giving a "talking down" impression. Thanks for digging in to understand this stuff.

While this code doesn't use `open`, it uses `PrivateKey.generate()`, a random number generator without a fixed seed, which is in the same category. Note where DisciplinedPython says:

> - other sources of non-determinism: random numbers, ...

IOU a bit more explanation, but I gotta run just now...

2021-06-25 19:00 UTC, Bill-Keuntje commented
> I think I marked this ready for review, did that take it out of draft and make it "a proper pull request"?

LOL. Sorry for my use of the word "proper", I should have said "non-draft" instead.
Yep, it's out of draft now, and I've approved. Dan's review requires updates to address the "ambient authority" https://github.com/rchain-community/rgov/pull/203#discussion_r658169928
I'm going to suggest we:
1) document the non-use of ocap discipline in the testing framework
2) open an issue to include ocap in a refactoring
3) merge this pull request

2021-06-26 03:12 UTC, dckc commented on pyrgov/README.md
> +new1 = PrivateKey.generate()
> Good point: "ambient authority" is not defined in/near the DisciplinedPython page.

I added a link to https://en.wikipedia.org/wiki/Ambient_authority

2021-06-26 03:33 UTC, w2vy commented
@dckc @Bill-Keuntje I created Issue 209 for Ambient Authority and 210 for pathlib
Please approve this pull request because the working branch is behind the inbox fix.

This will also allow us to handle a single problem in each issue which leads to less confusion

2021-06-26 03:43 UTC, dckc commented
I'd rather not skip step 1, "document the non-use of ocap discipline in the testing framework".

It's not normal to merge code that goes against project norms and then fix it later. The main purpose of pull request review is to maintain project norms in the main code branch. We can consider exceptions, but there should be some reason to do so.

Are you suggesting that "the working branch is behind the inbox fix" is the reason? I don't understand what that means. What is "the working branch"? What is "the inbox fix"?

I was expecting the rationale to take the form of a comment in the code, but perhaps that's not essential.

2021-06-26 04:18 UTC, w2vy commented
I think it should be clear to any idiot that I still have no idea what the real issue you are objecting to.
I see the pathlib improvement, but no clue what you are *specifically* complaining about

It is difficult to test this branch where it stands, I have no idea what you want changed and you seem to not want to explain in specifics what the issues are.

oh well this was fun and new people watching this that may not know everything already will not be encouraged to try to do any work

well done dan

2021-06-26 06:33 UTC, Bill-Keuntje commented
@dckc @w2vy @jimscarver @David405 
Wow. A lot can happen in a few hours. I guess I'll add my two cents.

@dckc https://github.com/rchain-community/rgov/pull/203#issuecomment-868940893 : <quote>The main purpose of pull request review is to maintain project norms in the main code branch</quote>
I disagree. "project norms" are not overarching. Each pull request and code review has its own main purpose.
@w2vy clearly does not understand what your ocap complaints/critiques are, and taking a stand on nebulous project norms is mere obstruction. Such a stand does not move the project or code forward, and discourages contributors. Approving PR contributions of less-than-perfect code and adding issues that address deficiencies allows contributors to add value. We have a label for such things: https://github.com/rchain-community/rgov/labels/ocap%20discipline.
RGOV, indeed the entire RChain cooperative, is voluntary. We cannot succeed without volunteers.

@dckc https://github.com/rchain-community/rgov/pull/203#issuecomment-868940893 : <quote>Are you suggesting that "the working branch is behind the inbox fix" is the reason? I don't understand what that means. What is "the working branch"? What is "the inbox fix"?</quote>
This statement indicates that you are not up-to-date on the current status of RGOV, its branches, its recent history, its code-base, or its contributors. Are you are aware that @w2vy has been donating (to us) his vacation time this last week?

@dckc https://github.com/rchain-community/rgov/pull/203#issuecomment-868940893 : <quote>I was expecting the rationale to take the form of a comment in the code, but perhaps that's not essential.</quote>
I agree a code comment is appropriate. In the time it took to compose your github messages, you could have easily made the code comment/documentation update and moved the code forward. Nevertheless, I will make the update myself in the hope that it satisfies your fury.

@w2vy https://github.com/rchain-community/rgov/pull/203#issuecomment-868945037 : oh well this was fun and new people watching this that may not know everything already will not be encouraged to try to do any work
While I understand that you are frustrated, statements like "Well done dan" are inappropriate.

2021-06-26 07:10 UTC, dckc commented
> > The main purpose of pull request review is to maintain project norms in the main code branch
> 
> I disagree. "project norms" are not overarching. Each pull request and code review has its own main purpose.

Ugh. now we have to go over norms in the whole open source / github community? [CONTRIBUTING docs](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) aren't clear enough?

> For contributors, the guidelines help them verify that they're submitting well-formed pull requests and opening useful issues.
>
> For both owners and contributors, contribution guidelines save time and hassle caused by improperly created pull requests or issues that have to be rejected and re-submitted.

Back to...

> @w2vy clearly does not understand what your ocap complaints/critiques are, and taking a stand on nebulous project norms is mere obstruction.

The norms are not nebulous. "anything globally accessible is immutable data" is there, in bold, in CONTRIBUTING.md. `PrivateKey.generate` is globally accessible (aka ambiently available, i.e. available just by writing it name, not by way of having it passed in as an argument) and not immutable data (the RNG state is mutated on each call, and quite likely includes data from some external source such as a clock or file).

I thought we were starting to have a useful exchange about what ocap discipline is, but then after I _specifically_ pointed out the similarity between `PrivateKey.generate` and `open`, the response I see is "I see the pathlib improvement, but no clue what you are _specifically_ complaining about". I've given several clues. I can give more on request.

2021-06-26 07:20 UTC, Bill-Keuntje commented
> > > The main purpose of pull request review is to maintain project norms in the main code branch
> > 
> > 
> > I disagree. "project norms" are not overarching. Each pull request and code review has its own main purpose.
> 
> Ugh. now we have to go over norms in the whole open source / github community? [CONTRIBUTING docs](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) aren't clear enough?
> 
> > For contributors, the guidelines help them verify that they're submitting well-formed pull requests and opening useful issues.
> > For both owners and contributors, contribution guidelines save time and hassle caused by improperly created pull requests or issues that have to be rejected and re-submitted.
Please see https://github.com/rchain-community/rgov/pull/203/commits/f0b5ec2eb5f851fe88cd9c2e117712a5a712d13a

> 
> Back to...
> 
> > @w2vy clearly does not understand what your ocap complaints/critiques are, and taking a stand on nebulous project norms is mere obstruction.
> 
> The norms are not nebulous. "anything globally accessible is immutable data" is there, in bold, in CONTRIBUTING.md. `PrivateKey.generate` is globally accessible (aka ambiently available, i.e. available just by writing it name, not by way of having it passed in as an argument) and not immutable data (the RNG state is mutated on each call, and quite likely includes data from some external source such as a clock or file).
> 
> I thought we were starting to have a useful exchange about what ocap discipline is, but then after I _specifically_ pointed out the similarity between `PrivateKey.generate` and `open`, the response I see is "I see the pathlib improvement, but no clue what you are _specifically_ complaining about". I've given several clues. I can give more on request.
Again, please see https://github.com/rchain-community/rgov/pull/203/commits/f0b5ec2eb5f851fe88cd9c2e117712a5a712d13a
And, I think @w2vy has requested more.

2021-06-26 07:20 UTC, dckc approved these changes
Thanks for continued work on integration testing.

I look forward to continued discussion of ocap security.

2021-06-26 07:24 UTC, merged

2021-06-26 07:34 UTC, dckc commented
> > Are you suggesting that "the working branch is behind the inbox fix" is the reason? I don't understand what that means. What is "the working branch"? What is "the inbox fix"?
> 
> This statement indicates that you are not up-to-date on the current status of RGOV, its branches, its recent history, its code-base, or its contributors.

Perhaps not; does that make it unreasonable to ask for clarification? git branches have exact names, and github gives them URLs; is it too much to expect clarity around such things? Among https://github.com/rchain-community/rgov/branches/all , there is no `working` branch. Perhaps he meant a branch with recent commits, i.e. `syntax-highlight`? But that's not the only branch with recent activity; I also see `rgov-use-pathlib` updated 5 days ago. Presumably "the inbox fix" has an issue or PR number; is it unreasonable to expect issues and PRs to be cited by number?

2021-06-26 07:41 UTC, Bill-Keuntje commented
Not sure how to help you here. I guess it might depend on the tools you are using. I agree that links to the branch/commit/PR would be helpful.
However, this is not a RGOV project/code subject. It's a communication subject, which we cannot enforce on others.

Maybe this helps
![image](https://user-images.githubusercontent.com/56281673/123506016-04aaaa80-d630-11eb-8fe8-dba50b289061.png)

2021-06-26 07:56 UTC, dckc commented
So the "inbox fix" is #205 . So "the working branch is behind the inbox fix" meant that the `pyrgov` integration tests on the `master` branch were outdated by #205?

OK, yes, I should have been able to figure that out. Sorry.