Port shell scripts to Node JS
rchain-community/rgov pull request #277
Opened 2021-12-17 08:07 UTC by Valentine-Mario

This PR aims at porting Shell scripts to node JS scripts

2021-12-18 07:19 UTC, Bill-Kunj commented
Excellent work. +1
An effort should be made to merge this quickly

2021-12-18 07:42 UTC, Bill-Kunj requested changes
Option to overwrite snapshot is necessary

2021-12-18 07:42 UTC, Bill-Kunj commented on bootstrap/check-rnode.js
> +    `ps aux |grep -v grep | grep "java .*rnode"|sed 's/[ \t][ \t]*/ /g'|cut -d' ' -f 2`,
@jimscarver We've had problems with this command in the past depending on platform. Can we verify that this works?

2021-12-18 07:42 UTC, Bill-Kunj commented on bootstrap/create-snapshot.js
> +  require('child_process').fork('stop-rnode.js');
I'm no JS expert, but is a fork required?
Could we just include/require the stop-rnode.js?

2021-12-18 07:42 UTC, Bill-Kunj commented on bootstrap/create-snapshot.js
> +  await exec_shell(`mkdir -p snapshot`);
Instead of exec_shell, does the node module 'fs' provide this functionality?

2021-12-18 07:42 UTC, Bill-Kunj commented on bootstrap/create-snapshot.js
> +    console.log('snapshot already exist');
This is correct, but I believe the existing shell script allows an overwrite option.

2021-12-18 07:42 UTC, Bill-Kunj commented on bootstrap/stop-rnode.js
> +    `ps aux |grep -v grep | grep "java .*rnode"|sed 's/[ \t][ \t]*/ /g'|cut -d' ' -f 2`,
@jimscarver Same comment from before: does this command work?

2021-12-18 07:42 UTC, Bill-Kunj commented on bootstrap/stop-rnode.js
> +      console.log('Aboring ...');
This text message could be either 'abhorring' or 'aborting'.
I'm laughing right now about the different interpretations of the message.....
:rofl:

2021-12-18 07:42 UTC, Bill-Kunj commented on bootstrap/stop-rnode.js
> +      console.log('Aboring ...');
...

2021-12-19 08:52 UTC, Valentine-Mario commented on bootstrap/create-snapshot.js
> +  require('child_process').fork('stop-rnode.js');
Yeah that could be done. But I wanted to execute the stop node without having to import it.

2021-12-19 08:52 UTC, Valentine-Mario commented on bootstrap/create-snapshot.js
> +  await exec_shell(`mkdir -p snapshot`);
Yeah. That skipped my memory. Would update the code

2021-12-19 08:53 UTC, Valentine-Mario commented on bootstrap/create-snapshot.js
> +    console.log('snapshot already exist');
Oh that makes sense. Would update the overwrite feature

2021-12-19 08:53 UTC, Valentine-Mario commented on bootstrap/stop-rnode.js
> +      console.log('Aboring ...');
🤣 🤣 🤣 🤣 Was a mistake on my path. Would fix right away

2021-12-25 05:48 UTC, Bill-Kunj approved these changes

2021-12-25 05:51 UTC, merged